# Nome do compilador
CC = gcc

# Flags de compilação
CFLAGS = -Wall -Wextra -std=c99

# Nome do executável final
TARGET = trabalho_final

# Arquivos de código-fonte
SRCS = deck.c jogo.c player.c pokedex.c trabalho_final.c

# Arquivos objeto correspondentes
OBJS = $(SRCS:.c=.o)

# Regra padrão que compila o programa
all: $(TARGET)

# Regras para compilar o executável a partir dos objetos
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Regra para compilar cada arquivo objeto
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Regra para limpar os arquivos compilados
clean:
	rm -f $(OBJS) $(TARGET)

# Regra para limpar e recompilar
rebuild: clean all

